<a href="https://colab.research.google.com/github/siddhiGharat/DSPY_Lab_Experiments/blob/main/Notebook3_miniproject_2402605_pdf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Dataset - Machine Learning Model

## Objective
The objective of this notebook is to:
- Define a machine learning problem
- Train a model using the cleaned dataset
- Evaluate model performance
- Follow the ML lifecycle

## Importing Required Libraries

In this step, we import the necessary libraries for building and evaluating the machine learning model:

- **pandas**: Used for data handling and manipulation
- **train_test_split**: Used to split dataset into training and testing sets
- **LogisticRegression**: Used to build the classification model
- **accuracy_score, confusion_matrix, classification_report**:
  Used to evaluate model performance

These libraries are essential for implementing the machine learning workflow.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Assuming 'titanic_cleaned.csv' is in your Colab Notebooks folder.
# If the file is located elsewhere or has a different name, please update this path.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/titanic_cleaned.csv")
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

    latitude   longitude  avg_temp  avg_humidity
0  32.746651 -125.564793     -5.52         30.01
1  71.186773   93.812101     29.67         93.29
2 -66.483926  -58.607089     -1.25         93.85
3  -9.602505  -55.154541      8.48         63.15
4  29.938939   85.044873     29.18         35.07

In [ ]:
import requests
import os

# URL of a publicly available cleaned Titanic dataset
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
output_file = "titanic_cleaned_public.csv"

# Download the file
response = requests.get(url)
response.raise_for_status() # Raise an exception for bad status codes

with open(output_file, 'wb') as f:
    f.write(response.content)

print(f"Downloaded {output_file} successfully.")

# Load the downloaded file into the DataFrame
df = pd.read_csv(output_file)
df.head()

Downloaded titanic_cleaned_public.csv successfully.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
import os

drive.mount('/content/drive', force_remount=True)

# List contents of the 'Colab Notebooks' folder
colab_notebooks_path = '/content/drive/MyDrive/Colab Notebooks/'

if os.path.exists(colab_notebooks_path):
    print(f"Contents of '{colab_notebooks_path}':")
    for item in os.listdir(colab_notebooks_path):
        print(item)
else:
    print(f"The path '{colab_notebooks_path}' does not exist. Please check your Google Drive structure.")

Mounted at /content/drive
Contents of '/content/drive/MyDrive/Colab Notebooks/':
DSPY_EXP-1_2402605
2402605_Exp2 _DSPY
2402605_EXP-3_DSPY.ipynb
2402605_EXP-5_DSPY.ipynb
2402605_EXP-4_DSPY.ipynb
2402605_Exp6_DSPY.ipynb
2402605_exp7_DSPY
2402605_EXP-8_DSpy.ipynb
2402605_EXp-9_dspy.ipynb
2402605_EXP-10_DSPY.ipynb
Notebook1_Data_Cleaning.ipynb
titanic_cleaned.csv
Notebook1_miniproject_2402605.ipynb
Untitled0.ipynb
 Notebook2_miniproject_2402605
Notebook2_miniproject_2402605 .ipynb
Untitled1.ipynb

## Problem Statement

This is a **classification problem**.

Goal:
Predict whether a passenger survived or not based on features such as:
- Passenger class
- Gender
- Age
- Fare
- Embarked

Target Variable:
- Survived (0 = No, 1 = Yes)

In [ ]:
X = df[['Pclass', 'Sex', 'Age', 'Fare']]
y = df['Survived']

## Feature Selection

Selected features:
- Pclass: Socio-economic status
- Sex: Gender
- Age: Age of passenger
- Fare: Ticket price

These features are chosen because they influence survival probability.

In [ ]:
display(df.head())

    latitude   longitude  avg_temp  avg_humidity
0  32.746651 -125.564793     -5.52         30.01
1  71.186773   93.812101     29.67         93.29
2 -66.483926  -58.607089     -1.25         93.85
3  -9.602505  -55.154541      8.48         63.15
4  29.938939   85.044873     29.18         35.07

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Train-Test Split

- 80% data used for training
- 20% data used for testing

This ensures the model is evaluated on unseen data.

In [ ]:
# Fill Age if still missing
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Fill Fare if needed
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())

# Fill Embarked if present
if 'Embarked' in df.columns:
    df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [ ]:
# Convert 'Sex' column to numerical using one-hot encoding
df = pd.get_dummies(df, columns=['Sex'], drop_first=True)

X = df[['Pclass', 'Sex_male', 'Age', 'Fare']] # 'Sex' column is replaced by 'Sex_male' after one-hot encoding
y = df['Survived']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Model Training

## Model Training and Prediction

In this step, a **Logistic Regression model** is used to perform classification.

- **Logistic Regression** is suitable for binary classification problems such as predicting survival (0 or 1).
- The parameter **solver='liblinear'** is used because it works well for small datasets and ensures stable convergence.
- **random_state=42** ensures reproducibility of results.

### Process:
1. The model is trained using the training dataset (`X_train`, `y_train`)
2. After training, the model learns relationships between input features and the target variable
3. Predictions are made on the test dataset (`X_test`) using the trained model

### Output:
- `y_pred` contains predicted survival values (0 or 1)

This step is crucial as it builds the predictive model and generates results for evaluation.

In [ ]:
model = LogisticRegression(solver='liblinear', random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.7821229050279329

In [ ]:
confusion_matrix(y_test, y_pred)

array([[87, 18],
       [21, 53]])

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.83      0.82       105
           1       0.75      0.72      0.73        74

    accuracy                           0.78       179
   macro avg       0.78      0.77      0.77       179
weighted avg       0.78      0.78      0.78       179

## Model Evaluation

Metrics used:

- Accuracy: Overall correctness of model
- Confusion Matrix:
  - True Positive
  - True Negative
  - False Positive
  - False Negative
- Classification Report:
  - Precision
  - Recall
  - F1-score

### Observation:
- Model achieves good accuracy
- Some misclassifications exist

### Conclusion:
The model performs reasonably well in predicting survival but can be improved further.

## Machine Learning Lifecycle

1. Data Collection – Titanic dataset
2. Data Cleaning – Handled missing values, removed unnecessary columns
3. EDA – Identified patterns and relationships
4. Feature Selection – Selected relevant features
5. Model Training – Logistic Regression
6. Model Evaluation – Accuracy, confusion matrix
7. Deployment – (Not implemented in this project)

## Final Conclusion

- Logistic Regression model successfully predicts passenger survival  
- Gender, class, age, and fare are important predictive features  
- Model achieves good accuracy with some misclassifications  
- Performance can be improved using advanced models  

Overall, the machine learning model effectively predicts survival based on selected features.