<a href="https://colab.research.google.com/github/siddhiGharat/DSPY_Lab_Experiments/blob/main/Notebook1_miniproject_2402605.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Titanic Dataset - Data Cleaning and Wrangling**

**Objective**

The objective of this notebook is to:

Load and understand the Titanic dataset

Perform data cleaning

Handle missing values

Perform data transformation and filtering

Prepare dataset for EDA and Machine Learning

Importing Required Libraries

We import essential Python libraries required for data handling and preprocessing:

pandas: Used for data manipulation and analysis
numpy: Used for numerical operations

These libraries form the foundation for working with structured datasets.

In [ ]:
import pandas as pd
import numpy as np

Loading the Dataset
The dataset is loaded using pandas read_csv() function.

This step reads the Titanic dataset file into a DataFrame.
The head() function displays the first 5 rows to understand the structure and columns.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/weather.csv')
df.head()

    latitude   longitude  avg_temp  avg_humidity
0  32.746651 -125.564793     -5.52         30.01
1  71.186773   93.812101     29.67         93.29
2 -66.483926  -58.607089     -1.25         93.85
3  -9.602505  -55.154541      8.48         63.15
4  29.938939   85.044873     29.18         35.07

**Dataset Description**

Dataset Name: Titanic Dataset

*   Dataset Name: Titanic Dataset
*   List item Source: Kaggle

*   Description: Contains passenger details such as age, gender, class, fare, and  List item survival status.


*   Objective: Analyze factors affecting survival.

## Understanding Dataset Dimensions

The `shape` function is used to determine:

- Number of rows (records)
- Number of columns (features)

This gives an idea of dataset size

In [ ]:
df.shape

(30, 4)

## Dataset Information

The `info()` function provides:

- Column names
- Data types of each column
- Number of non-null values

This helps identify missing values and data types.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   latitude      30 non-null     float64
 1   longitude     30 non-null     float64
 2   avg_temp      30 non-null     float64
 3   avg_humidity  30 non-null     float64
dtypes: float64(4)
memory usage: 1.1 KB

Statistical Summary
The describe() function gives summary statistics for numerical columns:


*   Mean
*   Median (via 50%)

*  Standard deviation
*   Minimum and maximum values

This helps understand data distribution

In [ ]:
df.describe()

        latitude   longitude   avg_temp  avg_humidity
count  30.000000   30.000000  30.000000     30.000000
mean    4.431988   -7.500551  13.469667     62.917000
std    51.199286   97.368684  14.779447     26.419587
min   -87.616802 -175.255532  -9.410000     12.510000
25%   -30.740467  -58.537624  -0.987500     43.442500
50%     6.867374   -3.927275  13.205000     65.170000
75%    49.721052   41.691478  28.205000     88.742500
max    81.900527  177.171816  37.060000     98.710000

Checking Missing Values


The isnull().sum() function is used to:

*   Identify missing (null) values in each column
*   Understand which attributes need cleaning

Handling missing data is critical for accurate analysis

In [ ]:
df.isnull().sum()

latitude        0
longitude       0
avg_temp        0
avg_humidity    0
dtype: int64

## Handling Missing Values

Different strategies are applied:

- **Age**: Filled with mean value (since it is numerical)
- **Embarked**: Filled with mode (most frequent category)
- **Cabin**: Dropped due to excessive missing values

This ensures dataset completeness.

## Filtering for Extreme Temperatures

To identify rows with extreme temperatures, we will filter the dataset based on `avg_temp` values. For this analysis, 'extreme' temperatures are defined as those below 0°C or above 30°C.

In [ ]:
# Filter for extreme temperatures (e.g., below 0 or above 30 degrees Celsius)
extremes_temp_df = df[(df['avg_temp'] < 0) | (df['avg_temp'] > 30)]

display(extremes_temp_df)

     latitude   longitude  avg_temp  avg_humidity
0   32.746651 -125.564793     -5.52         30.01
2  -66.483926  -58.607089     -1.25         93.85
6  -80.690573  -50.495757     -6.04         98.71
8   53.368069 -111.046002     -5.19         50.85
9   -3.446811   85.799680     37.06         75.93
10 -55.714929  -75.682896     35.90         96.05
13  57.250320  -38.215786     -0.23         81.39
14 -24.446480  177.074839     -6.57         12.51
15  -7.763391   24.541485     34.87         75.67
20 -56.874815  -15.336390     -5.81         33.13
23  25.466704  -46.089437     30.62         44.49
25  38.780003   11.914609     32.53         43.81
26  81.900527   12.852079     -9.41         45.97
27 -87.616802  -58.329227     -1.24         47.45

## Data Cleaning

Data cleaning involves:

- Removing duplicate records to avoid bias
- Converting categorical data into numerical format

Here:
- 'Sex' column is converted:
  - male → 0
  - female → 1

This makes the data suitable for machine learning models.

In [ ]:
# Remove duplicates
df.drop_duplicates(inplace=True)

# Convert categorical to numeric
# df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

In [ ]:
df.head()

    latitude   longitude  avg_temp  avg_humidity
0  32.746651 -125.564793     -5.52         30.01
1  71.186773   93.812101     29.67         93.29
2 -66.483926  -58.607089     -1.25         93.85
3  -9.602505  -55.154541      8.48         63.15
4  29.938939   85.044873     29.18         35.07

## Data Filtering and Feature Selection

Only relevant columns are selected for analysis:

- Survived
- Pclass
- Sex
- Age
- Fare
- Embarked

Irrelevant columns like Name, Ticket, and PassengerId are removed.

This reduces noise and improves efficiency.

In [ ]:
# Keep only relevant columns
# df = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked']]
df.head()

    latitude   longitude  avg_temp  avg_humidity
0  32.746651 -125.564793     -5.52         30.01
1  71.186773   93.812101     29.67         93.29
2 -66.483926  -58.607089     -1.25         93.85
3  -9.602505  -55.154541      8.48         63.15
4  29.938939   85.044873     29.18         35.07

## Final Dataset Verification

After cleaning and filtering:

- `info()` is used to confirm data types and absence of missing values
- `head()` is used to preview the cleaned dataset

This ensures the dataset is ready for further analysis (EDA).

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   latitude      30 non-null     float64
 1   longitude     30 non-null     float64
 2   avg_temp      30 non-null     float64
 3   avg_humidity  30 non-null     float64
dtypes: float64(4)
memory usage: 1.1 KB

In [ ]:
df.head()

    latitude   longitude  avg_temp  avg_humidity
0  32.746651 -125.564793     -5.52         30.01
1  71.186773   93.812101     29.67         93.29
2 -66.483926  -58.607089     -1.25         93.85
3  -9.602505  -55.154541      8.48         63.15
4  29.938939   85.044873     29.18         35.07

## Saving Cleaned Dataset

The cleaned dataset is saved as a CSV file so it can be reused in further analysis (EDA and Machine Learning).

In [ ]:
df.to_csv("/content/drive/MyDrive/Colab Notebooks/titanic_cleaned.csv", index=False)

## Final Conclusion

- Missing values were handled appropriately  
- Irrelevant columns were removed  
- Data was cleaned and transformed into suitable format  
- Important features were selected for analysis  

Overall, the dataset was successfully prepared for EDA and machine learning.